### ISSUE TITLE
在进行回答问题或者写文章时，编辑区时不时出现“本地保存成功”的提示。

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#12]
是不是可以不用这么频繁 甚至不用有着个提示？

**Comment by lbuu** [comment]
提示是表示已保存至草稿，不建议去掉。保存频率的建议是多少？

**Comment by pei-jikui** [comment]
建议加一个静态的“您的草稿会自动保存”之类的提示。如此频繁的体型，我个人感觉有些不好 。当然 ，这只是个人建议，您 可以根据实际情况操作。

**Comment by monsiprit** [comment]
感谢反馈~ 这应该跟编辑器相关，我们在寻找替代编辑器，还请耐心等待~

**Comment by pei-jikui** [comment]
> 感谢反馈~ 这应该跟编辑器相关，我们在寻找替代编辑器，还请耐心等待~
感谢

**Comment by pei-jikui** [comment]
> 感谢反馈~ 这应该跟编辑器相关，我们在寻找替代编辑器，还请耐心等待~

感谢

**Comment by pei-jikui** [comment]
编辑器换了，这个问题不存在了。
