### ISSUE TITLE
一个使用微信分享文章的 bug

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#14]
复现 步骤，
1） 点击文章下面分享按钮中的微信，弹出一个二维码，扫描 进行分享，或者取消分析。
2）再点击另外一篇文章下面的分享按，重复上面步骤，扫描得到的文章还是步骤1）中的文章，而不是新的文章。

**Comment by lbuu** [comment]
没有复现，请配图说明一下问题出现的步骤。

**Comment by pei-jikui** [comment]
分享了复现步骤。

**Comment by pei-jikui** [comment]
confirmed that it was resolved already.
