### ISSUE TITLE
问答列表里，答案数量不正确

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#15]
下面这个问题，明明有一个答案，但答案数却是0
![图片](https://user-images.githubusercontent.com/6623378/84450059-b7a4a200-ac81-11ea-81db-7801831391bc.png)

**Comment by russelltao** [comment]
Duplicate of 13#

**Comment by russelltao** [comment]
Duplicate of #13

**Comment by monsiprit** [comment]
已经修改bug，感谢反馈~

-新桥张魏康

**Comment by russelltao** [comment]
已验证
