### ISSUE TITLE
论坛首页中对“下载”“最新问题”的建议

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#2]
作为论坛，感觉下载放在首页并无多少必要。
同时，对于最新问题，它只能显示2个问题。建议是否可以一直滚动时，自然下拉无限显示？当然其他方式也行，目的是能够提供更多的信息量
![图片](https://user-images.githubusercontent.com/6623378/84219172-7934a900-ab02-11ea-87d8-71120d30d59f.png)

**Comment by LinuxSuRen** [comment]
确实是的，软件下载，放到一个菜单里就可以了。

**Comment by lbuu** [comment]
有两个问题需要确认：
1.之前是瀑布流布局，但是考虑无法放置版权信息而却掉。
2.另外一个是之前的会议觉得首页放文章内容太多，所以截止到目前的显示内容。

**Comment by monsiprit** [comment]
大家的需求已经收到，感谢大家的反馈~
个人建议：考虑到之前首页的改版情况，建议在迭代过程中，先确认具体需求，修改内容和修改目的，以便于我们进行需求排期与内容设计

-新桥张魏康

**Comment by monsiprit** [comment]
经会议讨论后决定，对首页进行优化设计并开发

**Comment by russelltao** [comment]
虽然还无法无限滚动，但下载已经替换为热门文章，这个问题暂时关闭
