### ISSUE TITLE
评论数与实际的评论条数不符

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#20]
![图片](https://user-images.githubusercontent.com/6623378/84624896-d2427980-af14-11ea-82a3-a5c1fe8452cb.png)
3条评论，但实际只有1条。
文章是这篇：https://www.nginx-cn.net/article/70?notification_id=652&item_id=84

**Comment by russelltao** [comment]
![图片](https://user-images.githubusercontent.com/6623378/84724748-81d22700-afbb-11ea-8d9e-8e5b6bbb103b.png)
这篇文章也是评论数量，与实际评论条数不符
https://www.nginx-cn.net/article/88?notification_id=675&item_id=93

**Comment by russelltao** [comment]
![图片](https://user-images.githubusercontent.com/6623378/84724889-dd9cb000-afbb-11ea-8a26-b0371a6c5c7f.png)
像这样去掉URL参数访问，评论就全了。这到底是不是算BUG呢？疑惑

**Comment by monsiprit** [comment]
从未读消息进去是为了能够快速定位未读的消息，所以其他消息不展示

**Comment by russelltao** [comment]
收到，理解
