### ISSUE TITLE
查看文章时，建议点击评论，可以直接跳到下方的评论区

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#21]
![图片](https://user-images.githubusercontent.com/6623378/84648471-ae445f80-af37-11ea-8eaf-efb9a1b40d11.png)
当文章过长时，滑到最下方的评论花时间，如果可以直接点击评论按钮，就跳到下方的评论，就方便很多。
另外，目前旁边的收藏、点赞、分享都能点击，就是评论不能点击，也有点怪

**Comment by pei-jikui** [comment]
Very similar as issue of No.16

**Comment by monsiprit** [comment]
好的，收到需求

**Comment by monsiprit** [comment]
已经修改

**Comment by russelltao** [comment]
已经修复，谢谢
