### ISSUE TITLE
修改个人信息时，保存时没有填个人介绍，但提示昵称未填，不允许保存

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#22]
![图片](https://user-images.githubusercontent.com/6623378/84716692-6d376400-afa6-11ea-8fd9-836080bf026b.png)
只是没填个人介绍，就提示昵称未填，且不允许保存。
1、提示错误；
2、个人介绍是选填项，不应该作为必填项处理。

**Comment by monsiprit** [comment]
已经更改后台设置字符限制，请陶老师验证，感谢反馈~

**Comment by russelltao** [comment]
已经修复，谢谢
