### ISSUE TITLE
建议：首页上的专栏关注按钮太过隐晦

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#23]
![图片](https://user-images.githubusercontent.com/6623378/84725248-c0b4ac80-afbc-11ea-9a0d-b81256ba9dfa.png)
这个灰色的爱心其实我过了好几天才知道它是干吗的。我觉得可以更直接点，不需要用户做推理，一眼看过去就知道这是关注，哪怕用汉字表示

**Comment by monsiprit** [comment]
收到，这块要不要针对首页的问题进行一下讨论，对首页的再改版再优化，我们统一处理，这样您觉得如何？

**Comment by russelltao** [comment]
可以的
