### ISSUE TITLE
专栏->文章  问题

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#24]
1）点击"专栏“->"文章” ，然后点击左侧"全部"
    出现的文章的列表的排序既不是最新，也不是最热。我们是不是考虑一个新的排序方式。比如最新发布的或者最热的文章？

2）新发布了一篇文章 “Nginx FTP 协议支持”，但是 在"专栏“->"文章” 所有的左侧类型中，都找不到对应的文章。

Thanks

**Comment by lbuu** [comment]
"Nginx FTP 协议支持"这篇文章没有显示是因为在编辑的时候选了“第三方插件”，所以显示在了第三方插件那里。   社区的设计上现在考虑的是个人信息的显示那里是不是将第三方插件和文章分开。

**Comment by pei-jikui** [comment]
> "Nginx FTP 协议支持"这篇文章没有显示是因为在编辑的时候选了“第三方插件”，所以显示在了第三方插件那里。 社区的设计上现在考虑的是个人信息的显示那里是不是将第三方插件和文章分开。

多谢！

**Comment by pei-jikui** [comment]
resolved. 后续需要把第三方插件和文章分开。
