### ISSUE TITLE
增加发表文章类型选项

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#26]
我们能不能像csdn那样，对于发表的文章提供几个类型。比如 原创 转载 翻译 等？

**Comment by LinuxSuRen** [comment]
好想法💡

**Comment by monsiprit** [comment]
这个我们之前在跟姜毅讨论过，是个不错的想法，我们可以放在下个版本迭代，这应该会是一个不错的功能，感谢jikui反馈~

**Comment by monsiprit** [comment]
文章分类标签已经上线了，请查验

**Comment by pei-jikui** [comment]
resolved。 Thanks
