### ISSUE TITLE
对问题的回答不能编辑。

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#28]
不知道是不是就这样设计的还是是个bug.
对一个问题的回答刚开始（大约不到一个小时内)还是可以编辑的，但是过一段时间以后，就没有编辑按钮了。

**Comment by monsiprit** [comment]
jikui，麻烦您截图看一下，我理解您的意思后去验证后显示我这里是可以进行编辑的，不知道是不是我这边理解有歧义

**Comment by pei-jikui** [comment]
上传图片到github还是失败。已经和魏康通过 微信分享了信息。

**Comment by monsiprit** [comment]
感谢jikui反馈，已经沟通解决，很细心的反馈~

**Comment by pei-jikui** [comment]
问题已经解决。
