### ISSUE TITLE
"信息发布“板块

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#29]
有没有可能提供一个类似信息发布 的版本，可以发布”招聘信息“，”求职信息“，甚至是谈天说地的信息？

**Comment by LinuxSuRen** [comment]
同意，可以增强用户粘性

**Comment by monsiprit** [comment]
这是一个好的建议，可以考虑在迭代过程中进行开发，已经记录

**Comment by pei-jikui** [comment]
发布文章中添加了“其他”模块。resolved.
