### ISSUE TITLE
社区统计中的“问答排名”不合理

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#3]
![图片](https://user-images.githubusercontent.com/6623378/84219285-be58db00-ab02-11ea-8ab6-94304e6e7f9a.png)
我觉得，将好问题放在最前面是对的，什么是好问题呢？
答案最多！答案获得的赞最多！
现在好像只是浏览量，这是不对的。

**Comment by LinuxSuRen** [comment]
同意，获得的赞多的答案说明是被认可的。

另外，建议在“问答排名”旁边加一个小问号的图标，点击后可以查看排名规则等信息。这样的话，对用户来说是一个良性的引导

**Comment by russelltao** [comment]
同意，排名规则对用户应当是透明的，用户会加强参与感。

**Comment by lbuu** [comment]
考虑通过小问好的形式增加排名规则说明。

**Comment by russelltao** [comment]
目前规则透明，此问题先关闭，后续针对规则再提新问题
