### ISSUE TITLE
建议取消游客的提问功能

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#36]
游客只能浏览，不能提问。
这既可以提升问题的质量，也有助于提问者与回答者的互动，也更方便论坛的管理。

**Comment by LinuxSuRen** [comment]
灰常同意，内容输出必须要有控制，不管是从质量还是从法律法规的角度来想。

**Comment by monsiprit** [comment]
收到，可以在下周运营会议上讨论一下

**Comment by monsiprit** [comment]
已经取消游客方式进行提问和发文，目前社区游客仅限于进行浏览，请您验证，陶老师

**Comment by russelltao** [comment]
已经验证通过，谢谢
