### ISSUE TITLE
issues 增加优先级的标签

### ISSUE THREAD

**Issue by LinuxSuRen** [nginx-zh/community#37]
为了便于大家对 issues 列表中的任务处理时分优先级，这样更加高效，也能知道轻重缓急。我提议增加优先级的标签：

* L0 需要优先紧急处理
* L1 相对重要的
* L3 小的改善

**Comment by russelltao** [comment]
同意，有些建议、BUG感觉是比较严重的，但无法标优先级，这样新桥同事很难明确处理顺序。

**Comment by monsiprit** [comment]
收到

**Comment by LinuxSuRen** [comment]
标签已添加
![image](https://user-images.githubusercontent.com/1450685/87535503-30a47880-c6ca-11ea-9c3c-9da73a1848c8.png)
