### ISSUE TITLE
【提议】快速形成结论，简单的问题，不需要在会议上讨论

### ISSUE THREAD

**Issue by LinuxSuRen** [nginx-zh/community#39]
自从我们启用 GitHub issues 依赖，大家相对比较活跃，也就产生了很多的想法、建议。如果要依赖我们的例会来讨论这些问题的话，就会导致决策链长、效率底下不恶性状态。
为了能够针对一些对于较小，影响面积不是很大的问题，我建议通过如下的方法来实现快速决策：
* 确定的若干人（例如：3个）都在对应的 issues 下留言同意
* 工时不超过一天

**Comment by russelltao** [comment]
同意

**Comment by jiangyidigital** [comment]
同意

**Comment by sunshineonthegreen** [comment]
1）跟新桥开发相关的问题由江毅负责
2）跟外部合作相关的事情由Sam， Jack Wang, Rick 三人负责
3）跟运营相关的问题由Rick，Betty，江毅和Sam四人负责
