### ISSUE TITLE
建议社区统计中，“代码贡献排名”暂时去掉

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#4]
![图片](https://user-images.githubusercontent.com/6623378/84219443-24ddf900-ab03-11ea-82e1-90bde7406fb6.png)
我猜这里是想统计第三方模块上传的数量吧？该不会是文章中列出代码的数量？
我觉得这个统计从当下的情况来看，没有太大意义，放在这里会干扰用户，**建议去除**。

**Comment by lbuu** [comment]
后续更新时代码贡献排行去除

**Comment by monsiprit** [comment]
陶老师，代码贡献排名已经去除，请您查验~

**Comment by russelltao** [comment]
已验证
