### ISSUE TITLE
建议：去除首页问答模块里的分享按钮

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#40]
只是看到问题的部分描述，正常情况下是不可能产生分享欲望的。
建议除了回答数，还可以加上这个问题及其所有答案共获得了多少个赞，这个可能对用户更有用一点。
![图片](https://user-images.githubusercontent.com/6623378/87667075-51d59980-c79c-11ea-85f9-911ec3a67f9f.png)

**Comment by monsiprit** [comment]
收到

**Comment by monsiprit** [comment]
陶老师，咱们首页改版已经完成上线啦，请您查验

**Comment by monsiprit** [comment]
陶老师，分享功能已经去除啦，点赞这块涉及到每个问题的和回复的赞的统计，这样统计的意义是不是不够具体，我们用该问题浏览量来代替，不知道这样是不是可以

**Comment by russelltao** [comment]
可以的，符合逻辑就好
