### ISSUE TITLE
nginx 官网mainline版本已经更新到1.19.1

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#42]
我们是不是也需要在本地和它保持同步？
另外，个人还是觉得自动化的同步对我们网站的维护有价值。可以减少很多人工时间。

**Comment by monsiprit** [comment]
收到，jikui。我们先手动更新，功能开发已经在排期中，优先级在积分和视频模块之后，不知道这样可以吗

**Comment by pei-jikui** [comment]
> 收到，jikui。我们先手动更新，功能开发已经在排期中，优先级在积分和视频模块之后，不知道这样可以吗

魏康，我个人觉得没有问题。 自动化的需求对应用户体验影响不大，它可能会影响我们潜在的运维的工作量。辛苦你们了！

**Comment by pei-jikui** [comment]
resolved  manually.
