### ISSUE TITLE
意见反馈

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#45]
用游客身份 提供了意见反馈，然后发现这些反馈的意见可以分享。通过微信扫描二维码分享的页面变成提问页面。
需要确认以下问题，
1，意见反馈需要分享吗？
2，如果可以分享，页面是要转到提问页面吗？

**Comment by monsiprit** [comment]
收到，谢谢jikui反馈~

**Comment by monsiprit** [comment]
jikui，在意见反馈页面，我们考虑后去掉了分享功能，请查验

**Comment by pei-jikui** [comment]
resolved.
