### ISSUE TITLE
登录页面的优先级建议以微信为主

### ISSUE THREAD

**Issue by russelltao** [nginx-zh/community#5]
![image](https://user-images.githubusercontent.com/6623378/84233838-b6f6f900-ab25-11ea-8785-9d946c1dc68b.png)
这是论坛当下的登陆窗口，以用户名、密码为第一登陆选择。
下面是CSDN的登陆，默认是微信扫码，我认为这种对微信用户、微信运营为主的nginx论坛来说，更合适：
![image](https://user-images.githubusercontent.com/6623378/84233945-e9a0f180-ab25-11ea-9552-adcd03de9f81.png)

**Comment by monsiprit** [comment]
收到，已进行需求安排，请陶老师耐心等待~

-新桥张魏康

**Comment by monsiprit** [comment]
经会议讨论后决定，对页面进行设计改版和开发

**Comment by russelltao** [comment]
已经解决！
