### ISSUE TITLE
个人信息中的文章数量和实际发表文章数量不匹配

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#7]
只发表里一篇，但是显示是3篇。有可能是把以前删除的文章也统计进去了？

**Comment by monsiprit** [comment]
bug已修改，感谢反馈~

-新桥张魏康

**Comment by pei-jikui** [comment]
还是有问题。
复现步骤，
1） 点击个人头像，可以看到文章数和实际数量相同。3篇。
2）点击自己的具体一篇文章，右侧的关于作者的信息中，文章数量是5篇，应该是把以前删除的文章也统计进去了。
咱们可以拿我的账号“皮皮鲁”做核对。
多谢。

**Comment by pei-jikui** [comment]
今天验证已经修改。
