### ISSUE TITLE
文章保存不生效

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#76]
文章保存以后，内容丢失。
步骤，
1） 从某一个网页比如 https://www.cnblogs.com/skynet/p/4173450.html  选择copy一些内容。
2） 发布文章，点击“富文编辑” control+v step 1)的内容。
3） 点击下面的保存草稿 。
4)  在个人动态 ->我的草稿 里可以看到有文章保存，但是打开以后，内容为空。

**Comment by monsiprit** [comment]
已经修改，请查验~

**Comment by pei-jikui** [comment]
resolved.
