### ISSUE TITLE
提议：文章标题添加类型

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#77]
我们发文章选择了“原创”，“转载”或者“翻译”类型以后，能不能把这些类型作为一个标签自动添加到文章的标题中？

**Comment by monsiprit** [comment]
收到，jikui，目前咱们社区是这样的，原创的标签是外露的，和文章一起，在标题的后面，在社区中就可以发现这点。转载和翻译我们选择隐藏，之所以这么做，是考虑到所有的文章都用标签进行标记的话，整个社区文章就会发现是眼花缭乱，遵循少即是多的原则，一个原创的标签已经满足了区分功能。所有我们在设计之初考虑以有标签和无标签进行文章类型区分，以原创标签外露从而鼓励大家积极发文，如果jikui您有更好的想法，欢迎留言讨论~

**Comment by pei-jikui** [comment]
魏康，感谢详细的解释。我个人可以接受。
多谢。
