### ISSUE TITLE
意见反馈的问题

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#78]
通过首页“联系我们'->"查看意见反馈” 进入意见反馈页面，出现如下问题，
1） 在第二个由 “御风” 提出的意见的右侧出现了“删除”选项，选择删除，提醒对话框是否真的删除。 
       问题   a )一般用户应该不具备删除别人意见的权限？ 
                  b) 为什么只有第二个条意见右侧出现了删除选项？
2) 点击意见下面的 “评论”选项，没有出现编辑框。没法回复。

**Comment by monsiprit** [comment]
收到，感谢jikui反馈~

**Comment by monsiprit** [comment]
jikui~问题已经修复，请查验，关于评论，是在下面输入框进行内容输入，后点击右侧评论按钮即可评论成功，评论成功后在输入框下面可以看到评论内容，如果有其他疑问欢迎沟通，感谢反馈~

**Comment by pei-jikui** [comment]
魏康，问题1a) 1b)都已经解决。

关于意见反馈，我个人觉得不是很重要的 一个环节，但是有些体验想分享一下。
1）按照现在的设计，我们只能对原始的意见进行评论。对于意见的评论不能再评论了。
2） 自己发布的 评论不能删除。
3） 现在打开意见反馈页面，默认每条意见下面都有一个很显著的评论按钮和文本输入框，我个人感觉不是很舒服。能不能默认不显示这个评论按钮和意见输入框。等用户想回复的时候，点击那个评论按钮再出现？

以上仅仅是个人建议，仅仅供大家参考。

多谢。

**Comment by pei-jikui** [comment]
3)已经解决。
