### ISSUE TITLE
【主页】 首页Banner左右翻动不方便

### ISSUE THREAD

**Issue by henryxqy** [nginx-zh/community#86]
首页Banner左右翻动只能靠下面小圆点点击，如果能在图片左右加入较大的箭头会提升使用体验

<img width="1318" alt="WX20200817-203045@2x" src="https://user-images.githubusercontent.com/33465711/90396409-be5bf500-e0c8-11ea-97b1-bc754927adf1.png">

**Comment by russelltao** [comment]
同意，我也有这感觉

**Comment by monsiprit** [comment]
已经修改，请查验

**Comment by monsiprit** [comment]
![image](https://user-images.githubusercontent.com/43594679/91114657-0081c980-e6bb-11ea-960c-9eb265d4e3d0.png)
