### ISSUE TITLE
论坛首页可不可以考虑把一些最新或者最热的文章放上去

### ISSUE THREAD

**Issue by pei-jikui** [nginx-zh/community#9]
文章和问答论坛比较活跃的内容，我们是不是可以考虑把他们都放到首页的位置，比如添加以下最新最热的文章，这样一进网站就可以吸引人的眼球。

现在如果要看文章的话，需要先点击网页上面的专栏->文章才能看到所有的文章列表。

**Comment by monsiprit** [comment]
咱们之前版本是有的，本着首页简洁的原因，咱们提出了修改删除，如果需要增加的话，还需要进行沟通确认~感谢反馈


-新桥张魏康

**Comment by pei-jikui** [comment]
resolved in  the new version.
